#!/bin/bash

scripts_folder="./scripts"

if [ ! -d "$scripts_folder" ]; then
  echo "Scripts folder not found."
  exit 1
fi

find "$scripts_folder" -type f -name "*.sh" -exec chmod +x {} \;

for script in "$scripts_folder"/*.sh; do
  if [ -x "$script" ]; then
    echo "[SCRIPTS] - Running $script"
    "$script"
  fi
done
